# Generated by Django 4.1.3 on 2023-05-24 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0020_remove_ownerreg_rights_ownerreg_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proapp.ownerreg'),
        ),
    ]
