# Generated by Django 4.1.3 on 2023-05-24 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0021_alter_property_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='oid',
        ),
    ]
