# Generated by Django 4.1.3 on 2023-05-24 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0023_remove_property_p4_remove_property_p5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='otype',
        ),
    ]
