# Generated by Django 4.1.3 on 2023-05-24 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0024_remove_property_otype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proapp.ownerreg')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proapp.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proapp.buyerreg')),
            ],
        ),
    ]
