# Generated by Django 4.1.3 on 2023-05-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0025_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
