# Generated by Django 4.1.2 on 2023-05-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0026_book_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='app_date',
            field=models.DateField(null=True),
        ),
    ]
