# Generated by Django 4.1.2 on 2023-05-24 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0027_book_app_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerreg',
            name='rights',
        ),
    ]
